### ISSUE TITLE
Userforms tests have some failures

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/recipe-form-building#2]
See Travis for more information. They pass in isolation but fail in the context of the recipe's test suite.

**Comment by NightJar** [comment]
Source of single remaining failure found: https://github.com/silverstripe/silverstripe-versioned/issues/127
Will try to see if we can reliably work around it for all core versions.

**Comment by NightJar** [comment]
Worked around, resolved in https://github.com/silverstripe/silverstripe-userforms/pull/728

**Comment by robbieaverill** [comment]
Just the postgres build to go https://travis-ci.org/silverstripe/recipe-form-building/jobs/344609335

**Comment by NightJar** [comment]
enabled PgSQL on the `userforms` travis config, no issues there. Running the build for this repo again, hopefully the results are reflected.

**Comment by NightJar** [comment]
All green! \o/
